### ISSUE TITLE
Permission problem with contributing

### ISSUE THREAD

**Issue by karenfreemansmith** [selftaughtprogrammers/resources#5]
Following the instructions to clone the repository directly gave me a permission error. In order to get the pull-request to work I had to fork the repository first and then clone my own copy to my local machine. We should probably update the contributing instructions to use forking instead of a direct clone. 

As an alternative, permissions could be changed for the group to allow direct contributions, but that has the potential to get pretty messy and open up the possibility of hacking.

**Comment by obsidianspork** [comment]
Thanks for bringing this up. I'll update the contribution guidelines @karenfreemansmith
