### ISSUE TITLE
Suggestion for beginner contributions

### ISSUE THREAD

**Issue by karenfreemansmith** [selftaughtprogrammers/resources#6]
I think we could also include a section in the contributions for beginners who are not comfortable with git yet to submit their suggestions as an issue instead of using pull requests.

**Comment by obsidianspork** [comment]
I think this is a great idea

**Comment by karenfreemansmith** [comment]
I found a couple YouTube videos about contributing that might also be helpful. This one has a real nice diagram about how to fork a repository and do pull requests. It's part 2 "the real way to contribute": https://www.youtube.com/watch?v=mENDYhfxH-o 

There is also a part 1 - the easy way, which shows how to contribute without the command line and other sometimes scary parts. 

I'd be happy to add these if you like.

**Comment by obsidianspork** [comment]
@karenfreemansmith absolutely!

**Comment by karenfreemansmith** [comment]
Working on it tonight...

**Comment by karenfreemansmith** [comment]
I thought there was an option to "close with pull request"...
